version: '3'
services:
  db:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./server/db:/data/db
  ui:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:8080
    volumes:
      - /app/node_modules
      - ./app:/app
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
